#!/usr/bin/env bash
# CORRECTION02-RESUME01 closure oracle.
#
# Verifies ALL invariants required to inherit the substantive gate log's
# PASS verdict at any later HEAD:
#
#   GATED_SUBJECT_ANCESTOR  = YES         (merge-base --is-ancestor)
#   POST_SUBJECT_DELTA      = ALLOWED     (no behaviour-affecting path)
#   C1_IMMUTABILITY         = YES         (the three historical files
#                                          are bit-identical to bde6045a)
#   DIFF_CHECK              = PASS        (rc=0)
#
# Exits nonzero if ANY check fails. Writes a SNAPSHOT file (not authoritative);
# the authoritative oracle is this script's exit status.
#
# Exit codes:
#   0  all invariants hold
#   1  gate subject not an ancestor of HEAD
#   2  post-subject delta contains behaviour-affecting paths
#   3  C1 historical evidence mutated relative to ENTRY_HEAD
#   4  diff-check HEAD failed
#   5  internal error

set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
cd "$root"
this=evidence/llvmspike01-resume01-correction01-resume01-correction02

ENTRY_HEAD=bde6045a200a1526435fd161f41b59e02df012b7
GATE_LOG="$this/gate-push-final.log"

ALLOWED_PATHS=(
  '^docs/'
  '^evidence/llvmspike01-resume01-correction01-resume01-correction01/'
  '^evidence/llvmspike01-resume01-correction01-resume01-correction02/'
)

C1_FILES=(
  'evidence/llvmspike01-resume01-correction01/red-1B.emit-llvm.ll'
  'evidence/llvmspike01-resume01-correction01/red-2.emit-llvm.ll'
  'evidence/llvmspike01-resume01-correction01/red-2.emit-llvm.txt'
)

if [ ! -f "$GATE_LOG" ]; then
    echo "FATAL: missing $GATE_LOG" >&2; exit 5
fi
SUBJECT_RAW=$(grep '^SUBJECT=' "$GATE_LOG" | head -1 | cut -d= -f2 || true)
if [ -z "${SUBJECT_RAW:-}" ]; then
    echo "FATAL: no SUBJECT line in $GATE_LOG" >&2; exit 5
fi
SUBJECT_FULL=$(git rev-parse "$SUBJECT_RAW^{commit}")
HEAD_FULL=$(git rev-parse HEAD)
SNAPSHOT_HEAD=${HEAD_FULL:0:7}
SNAPSHOT_SUBJECT=${SUBJECT_FULL:0:7}
SNAPSHOT_COMMIT_COUNT=$(git rev-list --count "$ENTRY_HEAD"..HEAD)

echo "[A] GATED_SUBJECT_ANCESTOR ..."
if git merge-base --is-ancestor "$SUBJECT_FULL" HEAD; then
    echo "    PASS: $SNAPSHOT_SUBJECT is ancestor of $SNAPSHOT_HEAD"
else
    echo "    FAIL: $SNAPSHOT_SUBJECT is NOT an ancestor of $SNAPSHOT_HEAD" >&2; exit 1
fi

echo "[B] POST_SUBJECT_DELTA ..."
DELTA=$(git diff --name-only "$SUBJECT_FULL"..HEAD)
BAD=$(printf '%s\n' "$DELTA" | grep -Ev "$(IFS='|'; echo "${ALLOWED_PATHS[*]}")" || true)
if [ -z "$BAD" ]; then
    echo "    PASS: all descendants in allowed paths (docs/, evidence/...01/, evidence/...02/)"
else
    echo "    FAIL: behaviour-affecting descendants exist after gated subject:" >&2
    printf '      %s\n' $BAD >&2; exit 2
fi

echo "[C] C1_IMMUTABILITY ..."
C1_DIFF=$(git diff "$ENTRY_HEAD"..HEAD -- "${C1_FILES[@]}")
if [ -z "$C1_DIFF" ]; then
    echo "    PASS: C1 files unchanged from $ENTRY_HEAD"
else
    echo "    FAIL: C1 files mutated since $ENTRY_HEAD:" >&2
    printf '      %s\n' "$C1_DIFF" >&2; exit 3
fi

echo "[D] DIFF_CHECK ..."
if git diff --check HEAD >/dev/null 2>&1; then
    echo "    PASS: rc=0"
else
    echo "    FAIL: diff-check HEAD non-zero" >&2; exit 4
fi

SNAP="$this/snapshot.txt"
{
    echo "# SNAPSHOT (regenerated by identity.sh — NOT authoritative)"
    echo "# Authoritative oracle: identity.sh exit status."
    echo
    echo "SNAPSHOT_HEAD           = $SNAPSHOT_HEAD"
    echo "SNAPSHOT_SUBJECT_SHORT  = $SNAPSHOT_SUBJECT"
    echo "SNAPSHOT_COMMIT_COUNT   = $SNAPSHOT_COMMIT_COUNT"
    echo "SNAPSHOT_AT             = $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$SNAP"

{
    echo "# SNAPSHOT (regenerated by identity.sh — NOT authoritative)"
    echo "# Authoritative oracle: identity.sh exit status."
    echo
    echo "ENTRY_HEAD        = $ENTRY_HEAD"
    echo "SUBJECT_SHORT     = $SNAPSHOT_SUBJECT"
    echo "SUBJECT_FULL      = $SUBJECT_FULL"
    echo "HEAD_FULL         = $HEAD_FULL"
    echo "COMMIT_COUNT      = $SNAPSHOT_COMMIT_COUNT"
    echo
    echo "GATED_SUBJECT_ANCESTOR = YES"
    echo "POST_SUBJECT_DELTA     = ALLOWED (docs/, evidence/...01/, evidence/...02/)"
    echo "C1_IMMUTABILITY        = YES (vs $ENTRY_HEAD)"
    echo "DIFF_CHECK             = PASS (rc=0)"
} > "$this/identity.txt"

echo
echo "OK: all invariants hold at HEAD=$SNAPSHOT_HEAD"